In [1]:
# 1(a)
import numpy as np
a=np.array([1,2,3,4])
add=a+2
add

array([3, 4, 5, 6])

In [2]:
#1(b)
multiply=a*3
multiply

array([ 3,  6,  9, 12])

In [3]:
#1(c)
divide=a/2
divide

array([0.5, 1. , 1.5, 2. ])

In [6]:
#2(a)
arr=np.array([1,2,3,6,4,5])
reverse=arr[::-1]
reverse

array([5, 4, 6, 3, 2, 1])

In [2]:
#3(a)
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
a=arr[0,1]
a


np.int32(20)

In [3]:
b=arr[2,0]
b

np.int32(70)

In [13]:
#4
import numpy as np
Harsheen=np.linspace(10,100,25)
print("Harsheen:",array)

Harsheen: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
print("Dimensions:",Harsheen.ndim)


Dimensions: 1


In [6]:
print("Shape:",Harsheen.shape)

Shape: (25,)


In [7]:
print("Total Elements:",Harsheen.size)

Total Elements: 25


In [8]:
print("Data Type:",Harsheen.dtype)

Data Type: float64


In [9]:
print("Total Bytes Consumed:",Harsheen.nbytes)

Total Bytes Consumed: 200


In [10]:
transpose=Harsheen.reshape(25,1)
print("Transpose:",transpose)

Transpose: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [14]:
transpose_T=Harsheen.T
print("Transpose_T:",transpose_T)

Transpose_T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [12]:
print("Shape after .T:",transpose_T.shape)

Shape after .T: (25,)


In [15]:
#5
import numpy as np
ucs420_harsheen = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])

In [16]:
print("Mean:",np.mean(ucs420_harsheen))

Mean: 43.333333333333336


In [17]:
print("Median:",np.median(ucs420_harsheen))

Median: 37.5


In [18]:
print("Max:",np.max(ucs420_harsheen))

Max: 90


In [19]:
print("Min:",np.min(ucs420_harsheen))

Min: 10


In [20]:
print("Unique Elements:",np.unique(ucs420_harsheen))

Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]


In [21]:
reshaped_ucs420_harsheen=ucs420_harsheen.reshape(4,3)
print("Reshaped array:",reshaped_ucs420_harsheen)

Reshaped array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [22]:
resized_ucs420_harsheen=np.resize(ucs420_harsheen,(2,3))
print("Resized array:",resized_ucs420_harsheen)

Resized array: [[10 20 30]
 [40 50 60]]


In [26]:
#2(b)
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    unique , counts = np.unique(arr,return_counts=True)
    max_count=np.max(counts)
    most_frequent_value = unique[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]

    return most_frequent_value, indices

most_freq_x, indices_x = most_frequent(x)
print("\nMost frequent value in x:", most_freq_x)
print("Indices in x:", indices_x)

most_freq_y, indices_y = most_frequent(y)
print("\nMost frequent value in y:", most_freq_y)
print("Indices in y:", indices_y)



 1st frequent value in x:
Indices in x: [0 5 7 8 9]

 1st frequent value in y:
Indices in y: [0 1 2]
